[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace.workspace = true
bootloader_api.workspace = true
linked_list_allocator.workspace = true

[features]
default = []
